const path = require('path');
const fs = require('fs');

const readdir = fs.promises.readdir;
const readFile = fs.promises.readFile;
const writeFile = fs.promises.writeFile;

// Template literals preserve the original file's line breaks (unlike
// JSON.stringify, which escapes them into one unreadably long line per
// file). Only backticks need escaping — none of these .sql files use `${`
// interpolation syntax or backslashes, so nothing else needs it.
const toTemplateLiteral = content => `\`${content.replace(/`/g, '\\`')}\``;

const generateModule = async (sourceDir, outputFile, exportName) => {
  const normalizedDir = path.normalize(sourceDir);
  const files = (await readdir(normalizedDir)).filter(
    file => path.extname(file) === '.sql',
  );

  if (files.length === 0) {
    throw new Error(`No .sql files found in ${normalizedDir}!`);
  }

  const entries = await Promise.all(
    files.map(async file => {
      const content = await readFile(path.join(normalizedDir, file), 'utf8');
      return [file, content];
    }),
  );
  entries.sort(([a], [b]) => a.localeCompare(b));

  const header =
    '// Generated by scripts/generateSqlModules.js — do not edit directly.\n';
  const fields = entries
    .map(([file, content]) => `  '${file}': ${toTemplateLiteral(content)},`)
    .join('\n');
  const body = `${header}export const ${exportName}: Record<string, string> = {\n${fields}\n};\n`;

  await writeFile(outputFile, body);
};

const run = async () => {
  const root = path.resolve(__dirname, '..');
  await generateModule(
    path.join(root, 'src/postgres/commands'),
    path.join(root, 'src/postgres/generated-commands.ts'),
    'commandSql',
  );
  await generateModule(
    path.join(root, 'src/postgres/migrations'),
    path.join(root, 'src/postgres/generated-migrations.ts'),
    'migrationSql',
  );
};

run().catch(err => {
  console.error(err);
  process.exit(1);
});
